### ISSUE TITLE
"In-game: When boss is killd game start lag" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#1]
Mods: AlchemistNPC 6.6, The Antiaris 0.1.0.4, Calamity Mod 1.2.4.2, Cheat Sheet 0.4.1.3, Dark-Assassin's Mod Library (DALib) 1.0.0.1, Elements Awoken 1.1.4, Enemy Affixes 1.0.1, Fargo's Mutant Mod: Summons and Souls 0.15.4, Hamstar's Helpers 1.3.7, Infinity - Endless Items 18.0, Loot Bags 0.13, Luiafk 1.0.0.125, Recipe Browser 0.5.2, Rewards 1.4.6.1, S-Pladison Mod 0.0.11.1, Terraria Overhaul 2.1.4, New Biome Fishing Crates 0.1.3
 
Is day: True, Time of day/night: 17196, Elapsed half days: 2
 
World name: 123, world size: Small
 
World progress: Eye of Cthulhu killed, King Slime killed, Queen Bee killed, Skeletron killed, Wall of Flesh killed, Destroyer killed, Twins killed, Skeletron Prime killed
 
Items on ground: 400, Npcs active: 11
 
Player info: Name: `asdfsda`, Male: True, Demon Heart: False, Difficulty mode: 0, Life: 1330 of 1330 (500) (20), Mana: 40 of 40, Defense: 162
 
Player equips: Head: Solar Flare Helmet, Body: Solar Flare Breastplate, Legs: Solar Flare Leggings, Accessory: Infinity Relic, Accessory: Soul of Dimensions, Accessory: Rampage Components, Accessory: Autoinjector, Accessory: Soul of Terraria
 
Player count: 1 (single-player)
 
 
 
Recent error logs:
```
Mod configs reloaded for AlchemistNPC, HamstarHelpers, LootBags, Rewards
```
 
So the problem is that when i try to kill the boss the game is turning from terraria to lagaria and i do not think that the mod is conflicting with others

**Comment by Mirsario** [comment]
If this still happens to anyone - I'll need a performance snapshot to know what's going on there at all. 

Guide from Discord:
> **How to record your performance issues with dotTrace:**
> **0.** Get dotTrace from <https://www.jetbrains.com/profiler/> (30 days trial is enough)
> **1.** Load Terraria with all your mods and open your world.
> **2.** Start dotTrace, click "Attach to Running App", click "Show All Processes", select "Terraria.exe", choose "Sampling" on the right panel, untick "Start Immediately", click "Run".
> **3.** A small "Profilling Controller" window will appear. Click the :pushpin: button to make it appear on top of other windows if it doesn't do that already.
> **4.** Switch back to your game. Press "Start" on the profilling controller.
> **5.** Run around in your game and make it lag.
> **6.** After half a minute or so, click "Get Snapshot and Wait" button on the profilling controller.
> **7.** Performance Viewer window will open. Select it and press Ctrl+S. Choose a convenient location for the snapshot. Then find it in Explorer, upload it to some file sharing site (MEGA / Dropbox / FileDropper) and post it.

Will keep this closed until someone gets me one.

**Comment by USMP-lancer** [comment]
first issue, and it submitted via a cursed util
