### ISSUE TITLE
Random bunny hopping

### ISSUE THREAD

**Issue by argv-minus-one** [Mirsario/TerrariaOverhaul#10]
Every once in a while, my character starts bunny hopping out of nowhere, even though the jump button is not held down.

This is usually only a minor annoyance, but it just got me killed by fall damage right after summoning Skeletron and spamming a bunch of potions and Beenades. Apparently, not only does it cause bunny hopping, it also causes the Spectre Boots to rocket upward as far as they'll go…which is more than high enough for the resulting fall to kill me. That is extremely frustrating.

I see most of the bug reports here are submitted by some in-game tool, but I can't seem to find it, so I'm submitting this bug report on GitHub manually. If you'd like me to submit the bug report in-game, please tell me how to do so. Thanks.

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
