### ISSUE TITLE
[Mod compatibility] Fargo's Mutant/Souls mod issues and whatnot [Multiplayer]

### ISSUE THREAD

**Issue by japesOfCakes** [Mirsario/TerrariaOverhaul#102]
Major bugs:
Using Fargo's purchasable boss spawners causes game desync upon boss death, resulting in items not dropping from player inventory when dropped, treasure bags becoming empty when opened.

Tested with daytime changers without boss, no desync
Tested with vanilla empress spawner, no desync upon boss death
Tested with boss checklist on and off, while using fargo's spawners, no different result.

Tested with Fargo's Empress of Light, Twins, King slime spawners. 
Result: Desync upon death, with above results.

Also Tested without Overhaul, which resulted in Empress becoming the ungodly bullet sponge she is. 
However, desync did not occur upon death.

Mod list
- Terraria Overhaul (V5.0 BETA 11/11B)
- Fargo's Best of Both worlds v0.2
- Fargo's Music Mod v0.1.1.2
- Fargo's Souls Mod v1.4
- Fargo's Mutant Mod v2.8.1
- Ore Excavator v0.6.6
- AlchemistNPC lite v1.8.13
- Boss checklist v1.3.3.1
- Recipe Browser v0.9.2.3 

Minor things:
Tungsten enchantment and it's improvements does not increase melee weapon hitbox size, but does slow down melee speed.

Unfortunately checking player and server logs didn't really seem to have anything of value to read on this.

Submitted a similar bug report to fargo's mods, and they suggested I attempt without overhaul.

Log here:
[server.log](https://github.com/Mirsario/TerrariaOverhaul/files/8836613/server.log)

Will update in comments about any other things I find.

**Comment by japesOfCakes** [comment]
- Bionumic Cluster's right click to zoom effect is does not function.

**Comment by motadv** [comment]
Can confirm, I tested the Fargo's bug and it has happened to me as well
Also, it's not only with Fargo's, it can happen with only vanilla bosses if multiple are spawned and killed at the same time (or if it has multiple parts?) Like all 3 mech bosses with double bosses or multiple parts

**Comment by Mirsario** [comment]
Is there desync still happening as of `v5.0-beta-11d`? The drop-related issues should definitely be resolved now.

**Comment by motadv** [comment]
I tried to desync the game really hard and couldn't replicate the bug anymore, killed 200+ bosses at the same time and it was running perfectly
Thank you so much!
