### ISSUE TITLE
[BUG][MANA REGEN][SFX] Mana Regen SFX is too loud at character's high movement speed. 

### ISSUE THREAD

**Issue by LordWillmont** [Mirsario/TerrariaOverhaul#103]
When the character has high speed, for example, while equipped with Hermes Boots or during a long fall, Mana Regen SFX becomes too loud.

It is also extra noticeable if played as mana-dependant classes (Warrior-Mage), as SFX becomes almost constantly accompanied during the entire period of the fight with the boss.

Please note, that changing SFX volume level in options does not help and seems to be not working properly at high falling speed.

**Comment by JonathanSwallow** [comment]
Just came to post this too aha. This is my only issue with the mod in 1.4

**Comment by Mirsario** [comment]
Both issues resolved in [13da80a](https://github.com/Mirsario/TerrariaOverhaul/commit/13da80a4d9be081a2eef25158479833e88e04f4b) and [de19c8c](https://github.com/Mirsario/TerrariaOverhaul/commit/de19c8c04a4a8472a74661c544b864315ba2a83b), which are in the just-released [v5.0-beta-11c](https://github.com/Mirsario/TerrariaOverhaul/releases/tag/v5.0-beta-11c).
