### ISSUE TITLE
"Reported from in-game: black background" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#11]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `Dual Wielding 1.0` | `Yet Another Boss Health Bar 1.3.2` | `Mod Helpers 4.4.0.1` |
| `HERO's Mod 0.2.5` | `Item Checklist 0.5.2` | `Even More Modifiers 0.1.2.3` |
| `Recipe Browser 0.7.3` | `Reduced Grinding 4.68` | `Terraria Overhaul 3.2.2` |
| `Add Vanilla Item Recipes 1.2` | `VeinMiner 1.3.0.5` | `WorldGen Previewer 0.3` |
| `Item Stats+ 1.3.2` | - | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Lamizor | True | False | 0 | 58 of 100 | 20 of 20 | 0 |
 
**Player Lamizor's (0) equipment:**
 
| - |
| :--- |
| - |
 
Is day: True, Time of day/night: 25769, Elapsed half days: 0
 
World name: The Opposite Realm, world size: Large
 
World progress: none
 
Items on ground: 6, Npcs active: 2
 
Player count: 1 (single-player)
 
Autopause: True
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: False
 
Screen resolution: 1920 1080
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
Initialized translations with 287 lines.
```
 
the background around my character is black

**Comment by Mirsario** [comment]
Been finally fixed in 4.0.4(.1)
