### ISSUE TITLE
1.4 11D "AlwaysShowAimableWeapons" not disabling in multiplayer

### ISSUE THREAD

**Issue by ChairmanDrek** [Mirsario/TerrariaOverhaul#110]
It's not an important issue, but this setting is always enabled in multiplayer regardless of settings, currently works fine in single player.

**Comment by Mirsario** [comment]
Configuration synchronization is probably not present at all yet...

**Comment by ChairmanDrek** [comment]
> 

What I mean is the setting stops working when the game is set to multiplayer, while it works as normal in single player, doesn't matter if I'm alone on my server.

**Comment by Mirsario** [comment]
> Configuration synchronization is probably not present at all yet...

That was an unrelated thing to say. The option was mistakenly marked as both-sided, while it should've been ClientOnly.
