### ISSUE TITLE
[1.4] Life & Mana pickups have very loud sounds

### ISSUE THREAD

**Issue by Hoabs** [Mirsario/TerrariaOverhaul#113]
Mini Mana Stars, that drop from enemies being killed by magic weapons, make a very loud noise when picked up.

**Comment by Mayul** [comment]
@Mirsario could you post the sound id for the mana pick so I can make a resource pack until this is addressed?

**Comment by Mirsario** [comment]
@Mayul good idea. it's `SoundID.Item30` or `Item_30`. Post the pack here for others too when you make it.

**Comment by Mayul** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2830616292

**Comment by Paladynee** [comment]
couldn't reproduce
