### ISSUE TITLE
Texture Error

### ISSUE THREAD

**Issue by ghost** [Mirsario/TerrariaOverhaul#118]
When killing a slime, my whole world starts to change textures into random stuff. Why does this happen?
I am on Linux Ubuntu 22.04 LTS and have an AMD GPU

**Comment by ghost** [comment]
alright, after some invastigation, the issue arrives, when a enemy/animal drops blood/slime. then for some reason the whole world gets "affected" by that slime but with random textures. i can mob them away, so im pretty sure its that. just dont know whats causing this to happen, nor how to fix this. the game is mostly unplayable like this, damn

**Comment by Mirsario** [comment]
Post screenshots and any `tModLoader-Logs/client.log` file.

**Comment by RexiWasTaken** [comment]
[/home/rexi/Bilder/Bildschirmfotos/Bildschirmfoto vom 2022-06-29 15-13-14.png](url)

**Comment by ghost** [comment]
i dont know how to upload images nor files. sorry :(

**Comment by ghost** [comment]
https://imgur.com/a/PHLeweD here are 2 screenshots

**Comment by ghost** [comment]
any news?

**Comment by Mirsario** [comment]
The screenshots look like you have really poor graphics drivers, you can try updating them.

In Steam, right click `tModLoader`, go to `Manage -> Browse Local Files`, head over to `tModLoader-Logs`, and drag and drop `client.log` into the message box here on GitHub.

It's likely that the game is running in OpenGL, which tends to be rather unstable between drivers and systems. You can try running with Vulkan by using `/gldevice:Vulkan` start argument (can be added in game properties in Steam), or, alternatively, if that doesn't work, you can try starting the game with the following shell command ran in the game's directory:
```
FNA3D_FORCE_DRIVER=Vulkan ./start-tModLoader.sh
```

**Comment by ghost** [comment]
[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/9033245/client.log)
there you go, hope this is what you wanted. also thanks, ima try those things.

**Comment by ghost** [comment]
so the second method worked, with the ./start and so on, but i had 2 fps then. so the graphic errors were gone, but now my game was lagging. damn i do hate my potato. thanks tho, i try updating my drivers, or reinstalling them or some shit
