### ISSUE TITLE
Medusa head game crash.

### ISSUE THREAD

**Issue by Dournbrood** [Mirsario/TerrariaOverhaul#12]
Using the uncharged Medusa Head weapon works perfectly fine and as intended, but while attempting to fight the Destroyer, if you charge the weapon completely, the game will crash upon the shot firing off. You'll still hear the damage tick off with a satisfying metal 'tink' but after that, the game is hardlocked for good.

No crash log is generated as the game never closes on its own.

**Comment by Mirsario** [comment]
> Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
> As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
