### ISSUE TITLE
crazy texture error

### ISSUE THREAD

**Issue by Captaindug** [Mirsario/TerrariaOverhaul#121]
![error problem thing](https://user-images.githubusercontent.com/108751447/177371142-7ff8b094-656e-44c9-9949-6de131180e31.png) i have a texture error where game textures are on blocks (even maps and things) and i can clean them with mop (im on mac btw)

**Comment by Mirsario** [comment]
Duplicate of #118, see my replies there.
Specifically: https://github.com/Mirsario/TerrariaOverhaul/issues/118#issuecomment-1172913693
