### ISSUE TITLE
Irregular crashes on mod loading

### ISSUE THREAD

**Issue by mindbound** [Mirsario/TerrariaOverhaul#13]
Every once in a while (with no obvious pattern or regularity), Overhaul v4 crashes the game with an `System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xna.Framework.Xact'` error, related to the music system. In addition, all game music stops during mod initialisation, which may or may not be related to this issue (it doesn't seem to appear in logs).

I'm using GoG Terraria 1.3.5.3, tModLoader 0.11.1, Terraria Overhaul 4.0, on Linux x86_64. Please see the log file attached.

[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/3368284/client.log)

**Comment by Mirsario** [comment]
Been fixed in 4.0.2, if I remember correctly.
