### ISSUE TITLE
Hooks can launch players up and/or sideways.

### ISSUE THREAD

**Issue by SiideCode** [Mirsario/TerrariaOverhaul#136]
Tested on the version 5.0.0.20 (Beta 11E).

How to reproduce:
1. Hold the "Up" button.
2. Use your hook. 
3. Jump when the hook is about to hit the surface.

Me reproducing it (result may not be the same with some hooks):

https://user-images.githubusercontent.com/94011931/180974347-4aa30c96-eafa-49a3-b9c8-63cdd45f61b0.mp4

**Comment by Mirsario** [comment]
Vanilla hooks had incorrect (shorter) ranges used in the swinging behavior. Fixed that now, but there's still a super slight teleportation happening at maximum range. I wonder if that's abusable.
