### ISSUE TITLE
Crash when clicking on "More Info" button in mod browser

### ISSUE THREAD

**Issue by mindbound** [Mirsario/TerrariaOverhaul#14]
When clicking on the "More Info" button in the mod browser, the game crashes with an `System.NullReferenceException: Object reference not set to an instance of an object` error.

I'm using GoG Terraria 1.3.5.3, tModLoader 0.11.1, Terraria Overhaul 4.0, on Linux x86_64. Please see the log file attached.

[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/3368311/client.log)

**Comment by Mirsario** [comment]
Been fixed in 4.0.1 1 day later.
