### ISSUE TITLE
Ambient Sound Issue

### ISSUE THREAD

**Issue by Lazaren00** [Mirsario/TerrariaOverhaul#144]
Hi, I have an issue with ambient sounds playing when they are not supposed to. For example if I am in the forest I hear birds chipping, but when I move to the desert or underground I can still hear them. Going back to the main menu does not help as the birds are still chipping. I have to quit the game and come back to silence the sound.

**Comment by Mirsario** [comment]
Couldn't seem to reproduce this. Is this still happening for you in `v5.0-beta-11f`?

**Comment by Mirsario** [comment]
Closing from lack of response; most likely been fixed in rewrites anyway.
