### ISSUE TITLE
Headless server can't start

### ISSUE THREAD

**Issue by jonesmz** [Mirsario/TerrariaOverhaul#145]
An error occurred while loading TerrariaOverhaul v5.0.0.20
It has been detected that this mod was built for tModLoader v2022.6.94.0
However, you are using tModLoader v2022.7.58.8
The mod(s) have been automatically disabled.

This is a linux headless server

**Comment by Mirsario** [comment]
I'll need more info than that - `tModLoader-Logs/server.log` at the very least.
Headless linux servers have been ensured to work a while ago.

**Comment by jonesmz** [comment]
I'm not able to reproduce. Apparently an issue with my local system.
