### ISSUE TITLE
"Reported from in-game: music and calamity" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#15]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AFK's PETS and more 9.9.8.4` | `Boss Checklist 0.2.1` | `Boss Cursor 1.2.1` |
| `Calamity Mod (No Calamity Music) 1.4.2.101` | `Calamity Mod Music 1.4.2.1` | `Calamity Mod Extra Music 1.0.7` |
| `\[c/FFD700\:Completion \| 10K DOWNLOADS\] 0.1.1.0` | `More Dialogue 0.2` | `Extensible Inventory 1.4.1.3` |
| `Fargo's Mutant Mod 1.3.6.2` | `Fargo's Soul Mod 0.7.3.1` | `Mod Helpers 4.4.0.5` |
| `imkSushi's Mod 4.3.1` | `Item Checklist 0.5.2` | `JPAN's Bags of Holding mod 1.4.1` |
| `Magic Storage 0.4.3.3` | `More Chest Loot 0.6` | `Nice Blocks 1.1.10000043` |
| `Pillar Items Plus 0.1.7` | `Recipe Browser 0.7.3.1` | `Reduced Grinding 4.68` |
| `Shorter Respawn Time 0.2.5` | `Solutions Mod 1.4.1` | `Summoners Association 0.3` |
| `Terraria Overhaul 4.0.2` | `Teleporters unchained 1.1` | `Wing Slot 1.6.2` |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Koris | True | False | 0 | 400 of 400 | 200 of 200 | 4 |
 
**Player Koris's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Vanity 1 |
| :--- | :--- | :--- | :--- | :--- | :--- |
| Wulfrum Headgear | Leinfors' Excessive Style | Leinfors' Fancypants | Fleeting Aglet | Angry Flipper | Leinfors' Hair Protector |
 
Is day: False, Time of day/night: 20770, Elapsed half days: 7
 
World name: HELP, world size: Large
 
World progress: none
 
Items on ground: 137, Npcs active: 11
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 1
 
Frame skip mode: 1
 
Is screen maximized: False
 
Screen resolution: 1280 800
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1.200001
 
UI zoom: 1
 
 
 
Recent error logs:
```
No error logs available.
```
 
Music boxes for calamity are not compatible :(

**Comment by Mirsario** [comment]
Been fixed with 4.1, forgot to close issues here.
