### ISSUE TITLE
Excessive mana drops breaks multiplayer worlds 

### ISSUE THREAD

**Issue by levarnu** [Mirsario/TerrariaOverhaul#151]
On a multiplayer server after spawning in a lot of gore (tested by killing eater of worlds ~70 times) you are no longer able to drop items (they get deleted completely) and treasure bags no longer spawn items (regular enemy drops still happen and can be picked up normally). This is even worse in Calamity only requiring 2-3 kills of Desert Scourge cause the same effect. Persistent until server reset.

**Comment by Mirsario** [comment]
Gore is clientside, so it couldn't be related. The reason was due to segmented enemies (worms) having all their segments drop mana on their own, causing too many items to be spawned.
