### ISSUE TITLE
how do i switch back to regular terraria music it wont go back and the discord server link doesnt work :(

### ISSUE THREAD

**Issue by TrollBlox** [Mirsario/TerrariaOverhaul#155]
I know this isnt where i should be asking but the discord link doesnt work :(

**Comment by Mirsario** [comment]
Overhaul's music is now implemented as a resource pack shipped through vanilla's workshop. You can go to `Workshop` -> `Use Resource Packs` to disable it.

+ Apparently the discord link had wrong casing on one letter, how annoying. Thanks for the reminder to check it.
