### ISSUE TITLE
Bee Hives Spawn in Houses.

### ISSUE THREAD

**Issue by DeltaJordan** [Mirsario/TerrariaOverhaul#16]
![image](https://user-images.githubusercontent.com/11305269/62330234-b27da080-b47d-11e9-910c-c5f1c9a0150b.png)

During summer, bee hives will spawn in buildings with player-placed walls. I'm not sure if this is intended but either way it is pretty annoying.

**Comment by Mirsario** [comment]
It's intended, although I might change it in the future. The only things that stop bee hives from appearing are light sources like torches & candles.
