### ISSUE TITLE
EoC not dying

### ISSUE THREAD

**Issue by nazmisyazwan90** [Mirsario/TerrariaOverhaul#17]
Overhaul Version 4.0.4.1

Tried killing Eye of Cthulu (EoC) to no avail.
Hp remains at 1 and EoC wont die

had calamity+thorium on alongside Overhaul
no issue with EoC if Overhaul is unloaded

Some other bosses tested with Overhaul loaded (all working fine ie:  they died properly):
- EoW
- Skeletron
- King Slime
- Bee Queen
- Golem
- WoF
- Plantera

EDIT:
EoC worked fine on an older map (map created with overhaul+calamity+thorium unloaded)
Not really sure what's the issue here

EDIT2:
Created a new world with all the mod listed. EoC died just fine on first few kills that I've done. Continued playing up to killing BoC, Skeletron & The Perforator (Calamity). Summoned EoC again, same bug occurs

EDIT3:
Seems to be caused by Calamity + Overhaul, Disabling either one would fix the issue

**Comment by SlouchingCat** [comment]
Also seeing this issue. Calamity and Overhaul alone cause this it seems.

**Comment by Mirsario** [comment]
Seems way more like Overhaul's fault this time, unlike the previous Calamity EoC issue (it didn't deal damage), which appears to be fixed. Does this only occur in their "Revengeance" mode? I'll look into this soon.

**Comment by nazmisyazwan90** [comment]
I did have "Revengeance" on in my playthrough. Can't remember if I did a test with revengeance off

**Comment by SlouchingCat** [comment]
Yes, it only seemed to happen with Revengance Mode enabled. EoC will remain at 1 hp and continue to make its Calamity death animation/death cry, but will not actually die.

**Comment by Mirsario** [comment]
Been fixed with 4.1, forgot to close issues here.
