### ISSUE TITLE
"For the Worthy" enemy stats broken

### ISSUE THREAD

**Issue by theluigiduck** [Mirsario/TerrariaOverhaul#175]
With "EnableDifficultyChanges" set to false, For the Worthy works fine in non-journey mode.
With it set to "true," enemy stats revert to just Master mode.
In Journey mode, it's even more broken.
With "EnableDifficultyChanges" set to false in Journey mode, enemy stats revert to just Expert mode.
With it set to "true," enemy stats revert to Master mode.
Disabling Terraria Overhaul set all these stats back to normal, so I can confirm that it is an issue with this mod.

**Comment by Mirsario** [comment]
Resolved in 54a6739ba7dc89f082c1fba4dd79e0f9741f20d1, which got pushed with `v5.0-beta-12c`.
