### ISSUE TITLE
Quirks after update to 4.0.4.1 (mod heavy)

### ISSUE THREAD

**Issue by tiger-uppercut** [Mirsario/TerrariaOverhaul#18]
we just updated to Terraria Overhaul 4.0.4.1 from 3.2.2, running dedicated, kept the world file

all reverted to normal and mostly stable (i know our mod combo is a bit much) after we went back to 3.2.2, so i can narrow it down to the update to overhaul 4.

issues we had:

players cant pick up certain loot and money
- but the other player can usually pick it up
- removing the ground below the item making it fall again usually helps picking it up
- the other player making floating items move a bit usually helps picing it up

heavy lag
- mobs are jumping around on the screen way more than before
- looks like regular network lag

pink sprites
- wyverns sometimes have some sprites of the chain in pink

null value in WorldResizeSystem
- one player randomly got the following msg in chat
Object reference not set to an instance of an object. at TerrariaOverhaul.OverhaulPlayer.PreUpdate() in (path to terraria)\ModLoader\ModSources\TerrariaOverhaul\Systems\Technical\Optimizations\WorldResizeSystem.cs:line 226
- sorry dont have the log for the full trace

disclaimer: were running a few mods
- Calamity
- Thorium
- Terraria Overhaul
- Expeditions
- Fishing 2
- some quality of life mods

**Comment by tiger-uppercut** [comment]
btw would be cool to have the source code public if that rolls with you.
often helps to understand whats going on

**Comment by tiger-uppercut** [comment]
oh and the game crashes when i fire the onyx blaster into a large amount of target dummies, but that might be any mod or combination thereof :)

**Comment by Mirsario** [comment]
> 
> 
> btw would be cool to have the source code public if that rolls with you.
> often helps to understand whats going on
I've been planning to release source code after refactoring it, which is something I've been doing for a very long time now, between the updates.

> 
> 
> oh and the game crashes when i fire the onyx blaster into a large amount of target dummies, but that might be any mod or combination thereof :)
Need log files for that.
> Path to the folder with Logs:
> On Windows: %userprofile%/Documents/My games/Terraria/ModLoader/Logs
> On Linux: ~/.local/share/Terraria/ModLoader/Logs
> On Mac: ~/Library/Application support/Terraria/ModLoader/Logs

**Comment by tiger-uppercut** [comment]
on the onyx blaster: the process just hangs, it doesnt crash. when i click windows asks to wait or close it.
doesnt create a terraria/modloader log file. when firing the gun the game slows down until it doesnt react. firing at a single or few dummies is not a problem. shooting at lots of enemies also hangs the process.

**Comment by USMP-lancer** [comment]
> on the onyx blaster: the process just hangs, it doesnt crash. when i click windows asks to wait or close it.
> doesnt create a terraria/modloader log file. when firing the gun the game slows down until it doesnt react. firing at a single or few dummies is not a problem. shooting at lots of enemies also hangs the process.

its probably halting the process with the amount of enemies you hit

**Comment by USMP-lancer** [comment]
dummies technically count as enemies themselves

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
