### ISSUE TITLE
Mining Helmet Issue

### ISSUE THREAD

**Issue by Samm73626** [Mirsario/TerrariaOverhaul#188]
After turning "EnableAimableFlashlights" to false, it completely disables the mining helmet, causing it to not emit any light at all.

**Comment by Mirsario** [comment]
This is resolved on the dev branch, but not yet released onto Steam, for I need to tackle some other issues.

Build instructions:
https://github.com/Mirsario/TerrariaOverhaul#%EF%B8%8F-how-do-i-build-this

**Comment by Mirsario** [comment]
Forgot to close this, was resolved in [v5.0-beta-13](https://github.com/Mirsario/TerrariaOverhaul/blob/dev/CHANGELOG.md?ts=4#50-beta-13).
