### ISSUE TITLE
Bow bug: still shooting non-unique arrows

### ISSUE THREAD

**Issue by UnbelieveableIdiot** [Mirsario/TerrariaOverhaul#19]
Well, I dunno what to add except for these two images, first is hellwing bow shooting normal arrows and doing nothing, second is bee's knees shooting same arrows, but converting them into water arrows for some incomprehensible reason

I tried different versions, 4.0, 4.0.3, 4.0.4.1, neither of them seems to fix the problem for me, tried to disable everything except for Overhaul, same result, works fine with Overhaul disabled, but what's the point to play without this mod, right?

I use Windows 7, oldish Samsung laptop, can send any possible information you'd need on reques as soon as I get to my pc

Thank you in advance, marvelous mod despite this one personal issue!

Hellwing
![Screenshot_2](https://user-images.githubusercontent.com/54120221/63051544-170d1680-bee6-11e9-8de9-6a908fad9248.png)
Bee's knees
![Screenshot_1](https://user-images.githubusercontent.com/54120221/63051546-17a5ad00-bee6-11e9-895f-117945144e66.png)

**Comment by UnbelieveableIdiot** [comment]
Btw Tome of infinite wisdom lost its right-click attack and instead fires pages only, not a big deal tho, does anyone else have these problems?

**Comment by Mirsario** [comment]
Been fixed with 4.1, forgot to close issues here.
