### ISSUE TITLE
not an issue but a question

### ISSUE THREAD

**Issue by abel1470** [Mirsario/TerrariaOverhaul#191]
since for some reason i cant join the discord ima ask through here:

What are the old gramophone songs? 

i noticed they changed but i cant find the old ones anywhere, so if posible, could you send me a list or a playlist with the old songs?

ty in advance

**Comment by Mirsario** [comment]
The 1.3 discs were documented on this old wiki here:
https://terrariamods.fandom.com/wiki/Terraria_Overhaul/Music_Discs

**Comment by abel1470** [comment]
> The 1.3 discs were documented on this old wiki here: https://terrariamods.fandom.com/wiki/Terraria_Overhaul/Music_Discs

yes, but I was refering to an older set of songs, I remeber that among them was awakening from space rangers 2

**Comment by Mirsario** [comment]
> yes, but I was refering to an older set of songs, I remeber that among them was awakening from space rangers 2

Right, those must've been newer than the wiki page actually.
The full list, from source code, would be:

| Identifier        | Title                          | Author/Source                   |
| ----------------- | ------------------------------ | ------------------------------- |
| Awakening         | Awakening                      | Space Rangers 2                 | 
| Bandit            | Bandit Radio                   | S.T.A.L.K.E.R.: Clear Sky       | 
| Blank             | Blank???                       |                                 |
| Circus            | Circus                         | Satan                           | 
| DrunkenSailor     | Drunken Sailor                 |                                 |
| FlyMeToTheMoon    | Fly Me to the Moon             | Evangelion                      | 
| GIJohnny          | G.I. Johnny                    | Magicka: Vietnam                | 
| HomewardBound     | Homeward Bound                 | Monty Python and the Holy Grail |
| KitchenAce        | Kitchen Ace (and Taking Names) | Bobby Prince                    | 
| MapleLeaf         | Maple Leaf                     |                                 |
| MontyPython       | Liberty Bell March             |                                 |
| MountainKing      | Mountain King                  | Kevin MacLeod                   | 
| Mystery           | it is a mystery                |                                 |
| NoHushing         | No Hushing                     | Raxxo                           | 
| OddCouple         | Odd Couple                     |                                 |
| Radio             | Radio                          | Frank Klepacki                  | 
| SuitePuntaDelEste | Suite Punta Del Este           | Astor Piazzolla                 | 
| TeaForTwo         | Tea for Two                    | Tommy Dorsey & Warren Covington |
| THUNDERDOME       | THUNDERDOME (Sector11)         | MashedByMachines                | 
| WelcomeToMyLair   | Welcome to My Lair             |                                 |

Most of the ones without a listed source are googlable by title, but what hellhole has `Circus.ogg` came from I have never found out, for example.
