### ISSUE TITLE
Lightning struck tree crashes client after collapsing

### ISSUE THREAD

**Issue by Classy-Cube** [Mirsario/TerrariaOverhaul#2]
Encountering a repeatable client crash when a jungle biome tree collapses after burning from a lightning storm. [PDB output](https://pastebin.com/vYDMrgf3) and the [file itself](https://drive.google.com/file/d/1FeE2sBqRh5n1qk96fAt3uUV5oUqLEPgd/view?usp=sharing). This [user post](https://drive.google.com/file/d/1FeE2sBqRh5n1qk96fAt3uUV5oUqLEPgd/view?usp=sharing) refers to the same bug. Only mod used is Terraria Overhaul on a dedicated server on the same IP but different PC. My client-crashlog.txt isn’t recording the crashes. I’ve not disabled any features of the mod. Thank you for your hard work, your mod has rejuvenated my love for Terraria.

**Comment by Mirsario** [comment]
Should be fixed in just-released '3.0'.
