### ISSUE TITLE
Killing Blow Localizations are Outdated.

### ISSUE THREAD

**Issue by Digum07** [Mirsario/TerrariaOverhaul#200]
All localizations still say killing blows double damage and require a damaged enemy despite the fact that killing blows were updated to only deal 1.5x damage and not require a damaged enemy.

**Comment by Mirsario** [comment]
^ Commit above rewrites English texts, but removes every other. I'll notify all translators now.
Also improves the look of the combat info text in general.

![image](https://github.com/Mirsario/TerrariaOverhaul/assets/6795251/9268f26f-da82-4a38-af1f-cc2c84ff053c)
