### ISSUE TITLE
Decal rendering is broken on specific or outdated drivers

### ISSUE THREAD

**Issue by Mirsario** [Mirsario/TerrariaOverhaul#217]
Decals render with an offset, perhaps a wrong matrix?

![image](https://github.com/Mirsario/TerrariaOverhaul/assets/6795251/4a3d96bc-ffef-45d9-9981-1df51e91bbb1)

Could not reproduce myself yet.

**Comment by mediawizard68** [comment]
PLEASE FIX THIS
![Uploading image.jpg…]()

**Comment by Mirsario** [comment]
Link to Starlight River has been disproven. One user of an `AMD Radeon RX 6600` GPU & Windows 10 has been able to resolve this by updating their GPU driver from `23.12.1` to `24.7.1`. Ideally this would be resolved to work on the former, as it can be a mistake in the used shader or rendering code. I own no AMD GPU, so another developer's help is needed.
