### ISSUE TITLE
Lack of Fall Damage with Veliocity Changes Disabled

### ISSUE THREAD

**Issue by TheRocked** [Mirsario/TerrariaOverhaul#223]
i was messing around with the config, disabled the changes, tried to fall with no accessories or anything for like space down to earth and survived no problem, probably change the fall damage minimum cap when the changes are disabled, back to vanillas fall damage height cap

**Comment by Mirsario** [comment]
Cannot reproduce.
https://github.com/Mirsario/TerrariaOverhaul/assets/6795251/efc953ac-5df7-4cad-9953-112a500e4ec0
