### ISSUE TITLE
Several issues and suggestions

### ISSUE THREAD

**Issue by Aizistral** [Mirsario/TerrariaOverhaul#23]
I've been playing for a while with your mod by now. By the way, gotta say it's fantastic in general and introduces a lot of good changes to Terraria. But I've also encountered several rather annoying issues with it, both visual and functional.
Overhaul is the only mod in my current pack (aside from Yet Another Boss Healthbar), so all bugs described below cannot be caused by something else.

1. There are rendering issues with items that are animated to be held by the player. Some of them give off light and glow themselves when swung (like Molten Pickaxe, for instance), but lighting is still applied to them in common ways when they are just held, so that they look dark and do not give off any light like other items. Just an inconsistency.
Also, whenever player is wearing any sort of cape, held items tend to overlap with it in unnatural ways:
![image](https://user-images.githubusercontent.com/47505981/71450995-6ce3ac00-276d-11ea-8b84-a8d9c600f007.png)
Default Terraria's animation (for when the item is actually used) shows how it should look like:
![image](https://user-images.githubusercontent.com/47505981/71451030-f2fff280-276d-11ea-9cda-f4a1696804a0.png)
I've also noticed, that when holding a kind of item that rotates to the direction of cursor when held, rendering of my character's default outfit bugs. You can see some excessive gray sprite pieces to the left, that should definitely not be here:
![image](https://user-images.githubusercontent.com/47505981/71451063-918c5380-276e-11ea-93f7-b49ab111ebe7.png)
This doesn't happen though when either wearing some kind of chestplate, or holding non-rotatable item like pickaxe:
![image](https://user-images.githubusercontent.com/47505981/71451089-f34cbd80-276e-11ea-8737-81491bd1414d.png)
Besides probably fixing that, I would also offer adding config option to turn off item holding animation, as I assume it may not work well in many more specific cases, and some might not like it in general.

2) When right-clicking Flying Piggy Bank (summoned by Money Trough), Overhaul doesn't count it as inventory interaction, and right-click ability of held item, if it has one (like Killing Blow of any broadsword) will also trigger, which is rather annoying.

3) Some magic weapons, like Razorblade Typhoon or Vile Crystal Shard, do not have any animation for right-click cast. Whenever right-click is pressed, some amount of time just passes without any visual indication of anything going on, before the cast actually happens. It actually makes it appear as if those weapons didn't get any special attention at all, and were changed in general pattern just for a checkmark.

4) Occasionally, when opening Repair Table, game might crash with following exception:
```
System.InvalidOperationException: Begin cannot be called again until End has been successfully called.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(SpriteSortMode sortMode, BlendState blendState, SamplerState samplerState, DepthStencilState depthStencilState, RasterizerState rasterizerState, Effect effect, Matrix transformMatrix)
   at Terraria.Main.RenderTiles()
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)
```
This sometimes happens under different circumstances, like when opening trading GUI of an NPC, but rarely and without apparent consistency.

5) As I've noticed, Overhaul actually makes it so that any dropped items and coins are saved along with saving the world, and therefore persist upon world reloads. I would offer to add config option to revert that behaviour to default, as sometimes it turns to be much more annoying than useful.

6) I would also offer to add specific config option to prevent lightning strikes from transforming sand blocks into glass in small area around them. When the world is played for at least few dozens of hours, nice naturally-looking deserts tend to turn into ugly mess of glass and sand.
In addition to that, would be also fine if your mod added some kind of upgraded lightning rod with much bigger range, maybe covering significant part of the world or entire world if we consider it to be end-game invention. Just as a way to globally deal with lightning strikes through gameplay rather than through messing around with config.

7) I actually like fire system in general, but it's one issue is that certain weapons also can set blocks aflame, like Meteor Staff, Flaming Arrows or imps summoned by Imp Staff. This basically makes them completely unusable outside of very limited number of environments (damn, even in Dungeon there are burnable shelves and furniture), and therefore much less versatile. Once again, I see solution in adding config option to prevent such items from setting blocks on fire, just as we have one to prevent torches from doing that. Maybe it would also make sense to add such option for lightning strikes.

8) Consider adding a config option to prevent player from always being oriented towards cursor position, so that direction they face will only change when character actually moves, like in vanilla. This might require additional work over head rotation animation, but in the end, you can just disable it for when this option will be enabled.

9) Many bosses have new death animations, and while it happens, they stay alive with 1 point of health and cannot be damaged. Some weapons though can actually deal damage to them, like overhauled Space Gun with it's primary attack, which results in bug when boss' corpse falls apart, but they actually remain in place, and therefore can be damaged over and over again spamming dead body parts, until death animation ends. The bug seems to be purely visual.

10) Speaking of Space Gun and it's primary attack, I suppose the energy beam it shoots is indended to last to the edge of the screen. On my screen, however, with dynamic camera enabled and when aiming around the screen corner, the length of the beam is not enough to reach the screen's edge. You can safely double or even triple the beam's length, since it is very limited and therefore even functionally inconvenient sometimes, as it can almost never reach targets that are offscreen, even if they are obviously there and there aren't any obstacles in way (like when fighting Old One's Army).

11) For whatever reason, your mod makes it so that when you use quick heal or quick mana, via keybinds or otherwise, the item use animation takes hold, interrupting usage of other items for a while, which is not the case on vanilla. For as insignificant as this change may appear, it actually makes severe impact on items like Mana Flower that use this behaviour. For instance, you cannot effectively use Last Prism combined with Mana Flower bacause of this, as each time potion is used, use of Last Prism is interrupted and has to be started over.
It should be at least controllable via config, besides that I don't see any viable reason to make it work like this at all, as such behaviour brings a lot of inconveniences in exchange for unnoticeable visual improvement.

**Comment by Mario90900** [comment]
I realize this post is about half a year old, but, I came to the issue tracker myself to see if something just like this was posted already. I just want to second these suggestions since a lot of them are asking for more config options, which is my biggest request. The mod is great and I enjoy a bunch of the features in it, but I would love it if you were able to add config options for as much as you can about the mod. With overhaul mods that change so much about the base vanilla experience, I feel like more config options lets the end user better pick and choose their own experience to what suits them.

Personally, I would love the option to turn off water evaporation entirely, as I find it just evaporating my oceans and other pools. Also being able to configure all aspects of lightning strikes, and other "world griefing" options in general  I believe the more config options the better when it comes to any aspect of the mod. In addition, I've also noticed a bunch of rightclick actions will sometimes also cause you to power attack. Sometimes when I talk to an NPC it power attacks, or sometimes if you hold down rightclick for just a tiny bit too long when shutting a door or opening up your magic storage, it power attacks.

**Comment by Mirsario** [comment]
> Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
> As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.

Most of this is no longer relevant with 5.0. Config requests are superseded by special issue posts for them. Feedback for features yet to be reimplemented will be considered -- I definitely won't re-add fire without serious design changes for it.
