### ISSUE TITLE
Weapons do.... Something

### ISSUE THREAD

**Issue by ncsasp** [Mirsario/TerrariaOverhaul#231]
I would just look at the attached video because I have no idea how to describe this. It happens with all weapons, and the bug disappears when overhaul is removed. 

Active Mods: 
Recipe Browser
Overheal
Fargo's Music Mod
Atmospheric Torches
Summoner UI
Fargo's Mutant Mod
Fargo's Souls Mod
Team Spectate
Shop Expander
Better Zoom
Overhaul (5.0.0.34)
Wing Slot Extra
absoluteAquarian Utilities
Chat Source
Boss Checklist
Census
Ore Excavator
TWAILA
Multiplayer Boss-Fight Stats
AlchemistNPC Lite
Magic Storage
Extra Pylons
Heart Crystal & Life Fruit Glow
Swap Loadouts While Using Items
Discord Rich Presence
Lan's Simple Healthbar
Where's My Items
WMITF
Portal Cursor
Cellphone is Wormhole

https://github.com/Mirsario/TerrariaOverhaul/assets/58613316/37f8882a-9387-4e24-ae5e-cdc3c5635e32

The Problem still exists without any other mods installed.

**Comment by Mirsario** [comment]
> ### F.A.Q.
> **Q:** I can't move, use items, etc.!
> **A:** Redownload the mod! TML `2024.02` should be loading Overhaul `5.0.0.38`!

**Comment by ncsasp** [comment]
Thank you! I couldn't find anything anywhere but apparently I didn't read the FAQ. Sorry!

**Comment by Mirsario** [comment]
It was only in the steam workshop description, so don't worry.
