### ISSUE TITLE
Overhaul won't update to 4.3.1

### ISSUE THREAD

**Issue by PKPeri** [Mirsario/TerrariaOverhaul#24]
When I try to update the mod in any way to the latest version, it gets stuck even though the bar is full. I've had my game open for hours at one point and nothing happened. Does it have to do with any other mods? Has anyone else had this issue? Thank you in advance.
![image](https://user-images.githubusercontent.com/59056103/72672632-13655900-3a5d-11ea-8a22-3e90912ea7cf.png)

**Comment by Extegral** [comment]
Also experienced this, had to update the mod manually. It's unlikely to be related to other mods as I didn't have any other enabled at the moment.

**Comment by PKPeri** [comment]
I tried redownloading, and now it straight up kicks me out a bit into the downloading process.

**Comment by Mirsario** [comment]
Ironically, this has been fixed in 4.3.1. Disable the mod, restart the game, and then update it through mod browser.
