### ISSUE TITLE
The cursor is very inconspicuous in battle

### ISSUE THREAD

**Issue by hairyf** [Mirsario/TerrariaOverhaul#242]
I don't like this cursor, it makes it difficult for me to find the cursor position during battles. I hope to adjust the size and shape

And it makes other cursor mods unusable, but I can't close it

**Comment by Mirsario** [comment]
It is toggleable and uses the outlined color of the base cursor - set it to contrasting values if you fail to track it.

**Comment by hairyf** [comment]
@Mirsario what I want to say is that I want to switch to a different cursor or restore the default cursor, rather than simply changing the color

**Comment by hairyf** [comment]
The mod should be able to set its off/display/size

**Comment by hairyf** [comment]
I use a 4k screen, which makes it very painful for me to play. It's too inconspicuous, and I can adjust the page proportions, but it will make the UI appear larger
