### ISSUE TITLE
Mild visual bug regarding the Spirit Flame

### ISSUE THREAD

**Issue by Csazker** [Mirsario/TerrariaOverhaul#252]
The Spirit Flame is supposed to be held in a static position, just in front of the player and with no directional movement whatsoever! I know this is a petty request, but it'd be nice to see it fixed.

**Comment by Csazker** [comment]
So, my first attempt was adding the code line into PlayerItemRotation:
```cs
if (Player.HeldItem?.type == ItemID.SpiritFlame) {
	Player.itemRotation = 0f;
	return; // Exit after setting rotation
}
```
But the arm still moves up and down instead of being fixed in the Use3 or Use4 positions - which I guess are the lowest arm positions and, as such, also the most appropiate.

This is weird, 'cause the Medusa's Head also has a locked arm position in Vanilla and the mod doesn't give it an aiming animation.
I will patiently wait for this to be fixed, since it's pretty smol and the mod is way too much of a masterpiece.

PS: I have heard Overhaul used to have a realistic gun reloading system? That sounds way too cool, I madly hope it doesn't get scrapped through the mod rebuilding.

**Comment by Mirsario** [comment]
The correct place to put the return was the `ItemCheck_ApplyUseStyle_Inner` injection, resolved in the commit above. The hardcode in the vanilla method is especially ugly, so going after ItemIDs is indeed as elegant as we can get, past hiding them in an array.

> PS: I have heard Overhaul used to have a realistic gun reloading system? That sounds way too cool, I madly hope it doesn't get scrapped through the mod rebuilding.

It is the only feature that is absolutely guaranteed to never come back, with the exception of non-gameplay-affecting reloading/pumping/levering visuals for shotguns and rifles. No point in arguing about this.

![image](https://github.com/user-attachments/assets/91458a76-08d7-44f7-a16b-b523f9f34886)

**Comment by Csazker** [comment]
Alright, thank you so much for the help!
