### ISSUE TITLE
Fatal New World Generation error and minor incovinence

### ISSUE THREAD

**Issue by SteamDoge9000** [Mirsario/TerrariaOverhaul#28]
I just installed this mod and have made a harrowing discovery that the world will not generate upon a new creation with this mod active

After doing some research, I found that it seems that the issue is resolved when set back to a date; before January 24th of this year.
Idk why but I heard this on the fourms and some users found that by ajusting their systems time to BEFORE this date that the issue is nonexistent. Hopes this is fixxed soon, I also hear the same is happening to Dragon Ball  Xeoverse 2 in terms of the game breaking after a date.

furthermore, It seems as if the mod has the mods, or games console open on defult

Thought this was a bug too until I found that it could be disabled,

Good luck

(The issue is non-existent when an existing world (unsure of if it being the same case as a previously generated world before this issue with this mod) and can only be encountered under the date conditons, with the lattest version of Tmodloader (lattest version as of this date, and replaced an older version [Complete wipe of old mod loader files and reinstall of game altogether] and the following mods enabled

[
  "BossChecklist",
  "HEROsMod",
  "CheatSheet",
  "YABSSM",
  "MagicStorage",
  "BossCursor",
  "CalamityModMusic",
  "CalamityMod",
  "DBZMOD",
  "ItemChecklist",
  "VeinMiner",
  "TerrariaOverhaul"
]

Hope this helps)

{additonal note: as of this current time of creating this report, the database for Tmodloader mods that connects the game to the database is unresponsive; just thought I should give you a head up.}

**Comment by Mirsario** [comment]
Overhaul's console opens for the first exception in a session. Reproduce the issue and post your client.log file from the following OS-dependent directory:

On Windows: %userprofile%/Documents/My games/Terraria/ModLoader/Logs
On Linux: ~/.local/share/Terraria/ModLoader/Logs
On Mac: ~/Library/Application support/Terraria/ModLoader/Logs

**Comment by Mirsario** [comment]
@SteamDoge9000 This is most likely an issue caused by Calamity Music. They're playing with injections without understanding anything about them, it seems. I cannot explain how they managed to screw up this bad. Will keep this open for now.

**Comment by Mirsario** [comment]
Recently released 4.4 will now disable calamity music's shenanigans through code injections.
