### ISSUE TITLE
Quest fish are unobtainable from fishing

### ISSUE THREAD

**Issue by ThaumicTom** [Mirsario/TerrariaOverhaul#29]
You cannot actually obtain any quest fish from fishing.

Mods used:
Terraria Overhaul 4.3.2.1

**Comment by USMP-lancer** [comment]
bro, did you check your fishing power?

**Comment by USMP-lancer** [comment]
cus its fine for me

**Comment by thaumictom** [comment]
This is 11 months old, still before 1.4 came out. Obviously it could've changed. Thanks for checking it out.
