### ISSUE TITLE
BoC Eternity Mode Conflict with Terraria Overhaul 

### ISSUE THREAD

**Issue by AlphaFromOmega** [Mirsario/TerrariaOverhaul#33]
While playing with a large mod pack containing Overhaul and Fargo's Soul Mod, I was fighting the Brain of Cthulhu when I thought I killed it as it was at 1hp and its death animation was playing until it started regenerating (A feature added by Eternity Mode) and the death animation stopped and the boss started attacking again, killing me. I turned off eternity to check it was indeed the cause and I was able to kill the BoC with no problem.

If this is an issue that needs to be fixed on Fargo's end I'll forward the issue to them.

**Comment by USMP-lancer** [comment]
its an issue taht can be fixed by either party, but will prob not be fixed by mirsario

**Comment by Mirsario** [comment]
No, I do intend on fixing this, but not in 1.3. It will likely disappear with the 1.4 reimplementation.

**Comment by USMP-lancer** [comment]
maybe

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
