### ISSUE TITLE
Rain,going underwater & desert ambient sounds causes out of memory

### ISSUE THREAD

**Issue by kazuviking2** [Mirsario/TerrariaOverhaul#38]
When rain starts the game is ok for a few seconds then out of memory.After falling into water the game freezes for a few seconds then its 50% crash or not crash and entering the desert with ambient sounds on insta crashes.A cool bug with calamity's snow ruffian armor set, you can go insanely fast with bunyhopping(pls dont remove it).

**Comment by Mirsario** [comment]
Rain and entering liquids has to load in audio, which allocates memory, so there's no surprises in here.

> Here's what you can do if you're getting an **OutOfMemoryException**:
> 
> **• If you were reloading mods - don't, instead it is recommended that you enable the mods you want and manually restart the game.**
> 
> **• If you have less than 6GB of RAM, closing down as many programs as possible could help.**
> 
> **• Be sure to not mix `Calamity`, `Thorium` and `Tremor`.
Use either one or none.**
> 
> **• Do not mix `Large World Enabler` with `Terraria Overhaul`, as the latter does the former's job already.**
> 
> **• Consider switching to unofficial 64-bit tModLoader. You can find it at https://discord.gg/DY8cx5T**

The latter doesn't sound like a bug either - bunnyhops are just somewhat OP.
