### ISSUE TITLE
[5.0] Implement a rich configuration GUI screen.

### ISSUE THREAD

**Issue by Mirsario** [Mirsario/TerrariaOverhaul#40]
The main reason why Overhaul always lacked configuration has always been that it used lame vanilla menus for it. There was just not enough screen space for everything, and adding new options has been a hassle. I've also never found TML's ModConfig to be good looking/modular enough (sorry, jopo) for Overhaul's planned hundreds of configuration options, so I've always planned to make my own screen. But I'm quite bad with GUI, and haven't yet got to do it.

What I've always imagined for this was a scrollable category screen with grids of trading-card-like image boxes that would lead to more ModConfig-like screens for lists of fields/properties. There will also have to be a search bar that would work on both screens, for both names of categories and their contents. I hope this is simple enough to visualize.

**Comment by Mirsario** [comment]
A sketch that makes you think 'amogus':
![image](https://user-images.githubusercontent.com/6795251/109391621-1487db80-7929-11eb-9ff0-7dccbd878039.png)

**Comment by Mirsario** [comment]
A HIGHLY PROFESSIONAL sketch that makes you think 'amogus':
![image](https://user-images.githubusercontent.com/6795251/109391638-25d0e800-7929-11eb-8895-ad7347fc9489.png)

**Comment by USMP-lancer** [comment]
i would love this, i would help but i have no idea how to do gui

**Comment by USMP-lancer** [comment]
perhaps one could use the code for the beastiary as a template to do this, it already has that kinda list to it, would take modifying tho
