### ISSUE TITLE
[5.0] Implement vast configuration

### ISSUE THREAD

**Issue by Mirsario** [Mirsario/TerrariaOverhaul#41]
### Accessibility
- `EnableAutoJump`
- [x] `EnableJumpInputBuffering`
- `ForceAutoReuse`
### Aesthetics
- `DestroyStumpsAfterTreeFalls`
- `EnableAimableFlashlights`
- `EnableTreeFallingAnimations`
### Ambience
- `EnableAmbientSounds`
- `EnableLowPassFiltering`
- `EnablePlayerFootsteps`
- `EnableReverb`
- [x] `EnableUnderwaterMuffling`
### Archery
- [x] `EnableArcheryArrowVisualization`
- [x] `EnableBowSoundReplacements`
- [x] `EnableBowFiringDelays`
- [x] `EnableBowChargedShots`
- [x] `EnableBowChargeHovering`
- [x] `EnableBowHoverJumps`
- [x] `EnableArrowFragments`
### Awareness
- `LowHealthAudioFilteringIntensity`
- `LowHealthSoundVolume`
- `LowManaSoundVolume`
- `ManaRegenerationSoundVolume`
### Balance
- `EnableBannerRework`
- [x] `EnableDamageRandomizationRemoval`
- `EnableDifficultyChanges`
- [x] `EnableHealthDropsRework`
- [x] `EnableManaDropsRework`
### Blood And Gore
- [x] `EnableAdvancedParticles`
- `EnableDecals`
- [x] `EnableGoreAudio`
- [x] `EnableGoreBleeding`
- [x] `EnableGoreBurning`
- [x] `EnableGoreGibbing`
- [x] `EnableGorePhysics`
- `EnableGoreStay`
- [x] `EnablePlayerCharacterGore`
- [x] `ParticleMultiplierSafe`
- [x] `ParticleMultiplierViolent`
### Camera
- `CameraSmoothness`
- `LimitCameraUpdateRate`
- `ScreenShakeStrength`
### Enemies
- `EnableEnemyLunges`
### Guns
- `EnableAimingRecoil`
- [x] `EnableAlternateGunFiringModes`
- [x] `EnableBulletCasings`
- [x] `EnableBulletImpactAudio`
- [x] `EnableGunSoundReplacements`
- [x] `EnableMuzzleflashes`
- [x] `EnableMinigunRecoilHovering`
- [x] `EnableStarCannonRecoilHovering`
### Interface
- [x] `EnableCrosshair`
- [x] `EnableCrosshairAnimations`
### Melee
- `EnableAxePowerAttacks`
- [x] `EnableAxeSoundReplacements`
- `EnableBroadswordPowerAttacks`
- [x] `EnableBroadswordSoundReplacements`
- [x] `EnableHammerSoundReplacements`
- [x] `EnableImprovedMeleeCollision`
- [x] `EnablePickaxeSoundReplacements`
- `EnableHammerPowerAttacks`
- `EnableImprovedMeleeAnimations`
- `EnableMeleeAirCombat`
- [x] `EnableMeleeAttackAiming`
- [x] `EnableMeleeKillingBlows`
- `EnableMeleeSwingVelocity`
- [x] `EnableMeleeVelocityBasedDamage`
- [x] `EnableMeleeVelocityBasedDamageIcon`
- `EnableProjectileSwordManaUsage`
### Movement
- `EnableAutoJump`
- `EnableBunnyhopping`
- `EnableClimbing`
- [x] `EnableDodgerolls`
- [x] `EnableDodgerollAudioCues`
- `EnableGrapplingHookPhysics`
- [ ] `EnableExplosionJumping`
- `EnableHorizontalAccelerationChanges`
- [x] `EnableRollJumps`
- `EnableVerticalAccelerationChanges`
- `EnableWallFlips`
- `EnableWallJumping`
### Magic
- [x] `EnableMagicSoundReplacements`
- [x] `EnableMagicPowerAttacks`
- [x] `EnableManaRegenerationRework`
- [x] `EnableManaRegenerationIcon`
### Music
- `EnableMusicPlaybackPositionPreservation`
- [x] `EnableBossDeathMusicStop

### Tweaks
- `DisplaySystemCursorWithDisabledUI`
### Visuals
- `AlwaysShowAimableWeapons`
- `EnableEnemyTiltingEffects`
- `EnableMeleeSlashVisualization`
- `EnablePlayerHeadRotation`
- `EnablePlayerTilting`
- [x] `EnableVisualWeaponRecoil`

**Comment by USMP-lancer** [comment]
on creating worlds with both evils, there is a mod for that in 1.3, fargos both evils, due to world gen changes this won't technically be applicable, but could be a great baseline for that feature, if someone makes a pull for it

**Comment by Mirsario** [comment]
Pretty much resolved with `v5.0-beta-14`. New requires should be their own issues.
https://mirsar.io/Posts/TerrariaOverhaul-v5.0-beta-14
