### ISSUE TITLE
Glitched description of certain mod items

### ISSUE THREAD

**Issue by NetImmerse** [Mirsario/TerrariaOverhaul#42]
for some reason modded accessories with stats/modes/etc. in item description behave like that (old text doesn't get removed on description update)
the only mods i have running are terraria overhaul and chaos rpg but this happens with other modded accessories (watch from time acceleration mod for example)

![x](https://user-images.githubusercontent.com/21229472/111026485-8b2dda00-83fb-11eb-83bc-b8ea0814e65f.png)

**Comment by Mirsario** [comment]
Well, does this happen with just that rpg mod? I don't think there are any changes to how tooltips work in overhaul.

**Comment by USMP-lancer** [comment]
i have a test, turn the crits overhaul off in config, then reload mods, see what changes

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
