### ISSUE TITLE
Gensokyo Mod's Weapon Alternate Abilities do not Function with Overhaul Enabled

### ISSUE THREAD

**Issue by Hotmud9** [Mirsario/TerrariaOverhaul#47]
Having both this mod and the Gensokyo mod enabled will render the alternate abilities of all of the Gensokyo Mod's weapons functionally useless, even the alternate ability is bound to a different key.

**Comment by USMP-lancer** [comment]
likely due to how the weapon overhauls are applied, disabled them in overhaul settings then test the weapons

**Comment by Hotmud9** [comment]
> likely due to how the weapon overhauls are applied, disabled them in overhaul settings then test the weapons

Disabling the item overhauls doesn't fix it, either.

**Comment by USMP-lancer** [comment]
see if you can have gensokyo load after overhaul perhaps

**Comment by Hotmud9** [comment]
> see if you can have gensokyo load after overhaul perhaps

How would I go about doing that?

**Comment by Mirsario** [comment]
> 
> 
> see if you can have gensokyo load after overhaul perhaps

TML does not have a concept of customizable mod load orders, and they nearly never matter.

**Comment by Hotmud9** [comment]
> > see if you can have gensokyo load after overhaul perhaps
> 
> TML does not have a concept of customizable mod load orders, and they nearly never matter.

I _thought_ that was the case.

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
