### ISSUE TITLE
Auto Select Locking not working properly. [BUG]

### ISSUE THREAD

**Issue by FelisMoon** [Mirsario/TerrariaOverhaul#48]
[BUG REPORT]

 **All auto select locks seem to not work properly.**

_Expected behavior_: While shift is held, auto select should swap to pickaxes when looking at in range blocks, axes looking to trees, torches when looking at walls and out of range blocks and water lights while looking to water. 
When an action is confirmed with a click, it should be locked until the click is released. (say you're mining with auto select, it shouldn't stop mining until you let the click go, letting shift go shouldn't cancel auto select's selection until the click is lifted) and if the mouse hovers over something that is not a block while the action is already selected, auto select should not swap to other item (say, torches when mouse is on walls or air) until the click is lifted.

_Actual behavior_: While shift is held, auto select swaps to pickaxes when looking at in range blocks, axes looking to trees, torches when looking at walls and out of range blocks and water lights while looking to water. 
When an action is confirmed with a click, the action IS NOT locked as intended. 
- If shift is let go while the click is held, auto select is cancelled and you return to your last item in your hotbar. Auto Select should be cancelled when the action is finalized by releasing click regardless of shift being held or not. _Auto Select should work as a selector confirmed by clicking._
- if the held mouse cursor hovers over a different tile type or (when mining with smart cursor) an out of range tile, auto select interrupts the action and performs the one the cursor is over. this causes issues like players placing unwanted torches while mining as soon as the block their cursor is over is destroyed. If the player selects the pickaxe and holds down the click, the action shouldn't change until the player releases the click, no matter where the cursor moves next. (Players more likely want to mine with smart cursor activated while the cursor is far away from the tile blocks in range)

**Comment by Hadari-xX** [comment]
Here's some videos displaying this.

Normal (recorded in 1.3 but functions the same in 1.4)
![pick](https://user-images.githubusercontent.com/82526756/116830549-02b8f380-ab79-11eb-8b7e-5ea2cd8c7b2b.gif)
1.4 Overhaul
![pick2](https://user-images.githubusercontent.com/82526756/116830556-0e0c1f00-ab79-11eb-8b60-e4e1eb06e968.gif)

**Comment by FelisMoon** [comment]
This issue seems to be fixed in last version (v5.0 BETA 11D)
