### ISSUE TITLE
Expert Mode Loot Bags Not Dropping

### ISSUE THREAD

**Issue by votex09** [Mirsario/TerrariaOverhaul#5]
Most likely MP issue:
A friend and I noticed 100% of the time, on the first kill, bags would not drop.  We had to kill multiple times to get a bag.

Without Overhaul, bags drop every time.

![image](https://user-images.githubusercontent.com/10671494/45054230-fbe92400-b051-11e8-89e2-7749ef9f07a4.png)
This is, more or less, my modlist.

**Comment by Mirsario** [comment]
Should be fixed in just-released '3.0'.
