### ISSUE TITLE
[5.0] Magic and Gun attacks cause insane screen shake and other weirdness for other players

### ISSUE THREAD

**Issue by AJMJ2012** [Mirsario/TerrariaOverhaul#52]
In multiplayer, attacking with magic weapons or guns other nearby players get insane screen shake.
Additionally guns also seem to have insane item rotation and the muzzle flash stays around for a lot longer. Non shotguns also eject a huge amount of casings.

**Comment by Mirsario** [comment]
Has been fixed in BETA 6.
