### ISSUE TITLE
"In-game: zoomed in screen" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#6]
Mods: Calamity Mod 1.3.4.1, Consolaria. Console exclusives and more. 1.0.5, Mod Helpers 3.1.0.4, imkSushi's Mod 4.3.1, LightPets 1.0.5, Rewards 2.0.0, Terraria Overhaul 3.1.2, VeinMiner 1.3.0.5, Which Mod Is This From? (WMITF) 2.6
 
Is day: True, Time of day/night: 14722, Elapsed half days: 134
 
World name: LO Maps & Treasure, world size: Large
 
World progress: 
 
Items on ground: 66, Npcs active: 6
 
Player info: Name: `Vriska Serket`, Male: False, Demon Heart: False, Difficulty mode: 0, Life: 140 of 140 (120), Mana: 140 of 140, Defense: 11
 
Player equips: Head: Ancient Shadow Helmet, Body: Iron Chainmail, Legs: Iron Greaves, Accessory: Precise Climbing Claws, Accessory: Rash Aglet, Accessory: Spiked Cloud in a Bottle, Accessory: Mana Jelly, Accessory: Lucky Guide to Plant Fiber Cordage, Vanity: Witch Boots
 
Player count: 1 (single-player)
 
 
 
Recent error logs:
```
Initialized translations with 284 lines.
Rewards updated to 2.0.0
0:000:00000 - 000037.72   RewardsWorld.Initialize
0:000:00001 - 000038.20   RewardsWorld.Initialize
```
 
my screen is zoomed in like when talking to an npc but it will not unzoom

**Comment by Mirsario** [comment]
I believe this was fixed in 3.2. Reopen if it ever occurs again.
