### ISSUE TITLE
[1.3] Accessories and Huntress wig does not work with Overhauled player animations

### ISSUE THREAD

**Issue by Unknowneth** [Mirsario/TerrariaOverhaul#60]
This bug existed in the 1.3 version and even till this day it still does. Basically, hand accessories like shackles, rings and gloves do not follow the improved hand animations and still play the vanilla version. Same with huntress wig and some head accessories. The huntress wig's ear does not follow head rotation and so do some head accessories.

**Comment by USMP-lancer** [comment]
shackle could use some jiggle bones yes

**Comment by Mirsario** [comment]
![image](https://user-images.githubusercontent.com/6795251/117997699-defd6680-b34b-11eb-8726-1ed3f515e015.png)
There are no such issues in 5.0 (1.4).

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
