### ISSUE TITLE
[5.0] Bone glove bug when holding a weapon

### ISSUE THREAD

**Issue by Unknowneth** [Mirsario/TerrariaOverhaul#63]
If you equip the bone glove and then hold a weapon that has its own holding animation added by Overhaul, the game thinks you are attacking and it won't stop firing crossbones. Mostly happens with bows, swords and staves.

**Comment by Mirsario** [comment]
This was a TML bug. Just fixed it with https://github.com/tModLoader/tModLoader/pull/1601
(Will appear on mergedtesting soon)
