### ISSUE TITLE
[1.3] Weapon icon showing when disabled in options.

### ISSUE THREAD

**Issue by BBllanc** [Mirsario/TerrariaOverhaul#68]
I thinks there's a problem related to weapon UI option. Even when I disable it in the menu I still see the little icon in the bottom left corner. Wouldn't be a thing to bother, but as I'm using Leveled mod some text overlaps each other during level up.

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
