### ISSUE TITLE
In-game: everything deals only 1 damage

### ISSUE THREAD

**Issue by LexP88** [Mirsario/TerrariaOverhaul#7]
I'm playing the latest release of Overhaul on a Mac, with tMod 0.10.1.5, and every damage instance to and from my character is reduced to 1 with the exception of fall damage and charged melee attacks (broadswords, hammers etc). Boulders and antlions manage 4 damage, and explosives also seem to kill me normally, but beyond that even with 0 defense mobs can't damage me, and I can only damage them with charged melee attacks, everything else (spears, bows, shuriken, staffs etc) only deals 1 damage, even to critters. I tried making new characters and new worlds on different difficulty settings but the problem persists. If I'm not the only one encountering this issue I really hope it can get fixed, I love this mod otherwise. Keep up the good work! :)

**Comment by Ristovski** [comment]
Can confirm same issue present on Linux. This is quite odd.

**Comment by Mirsario** [comment]
Been fixed in 3.3. (Haven't been keeping track of Github issues, now I do).
