### ISSUE TITLE
[5.0] Climbing while using Bunny Paw cause Player char stuck on jumping animation.

### ISSUE THREAD

**Issue by atusmk2** [Mirsario/TerrariaOverhaul#73]
When trying to climb while jumping using bunny paw, player char stuck in jumping animation, and when you remove it, they got back to where the player supposed to climb before.
Tried on Beta 8.

[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/6866013/client.log)

[Example video.](https://cdn.discordapp.com/attachments/712282214137593938/867673712714842142/2021-07-22_14-36-46.mp4)

**Comment by Mirsario** [comment]
Issue in `1.4_contenttags` of TML. Worked around in [5d3dcea](https://github.com/tModLoader/tModLoader/commit/5d3dcea68b2d0dd6bec02d9ce69975dc07acc21f) of it. As the commit states, that branch sucks.
