### ISSUE TITLE
[1.3] Onyx Blaster 9000 in the equipped inventory slot and Bug Net in the quick item menu causes the weapon to shoot multiple projectiles at once.

### ISSUE THREAD

**Issue by Max-Spec** [Mirsario/TerrariaOverhaul#75]
Trying to use the Bug Net while having Onyx Blaster 9000 on you causes it to shoot multiple projectiles in a spread pattern, like the vanilla(?) Onyx Blaster but with Overhaul's projectiles. It's incredibly overpowered as it uses only 1 dark matter ammo per shot like this.

**Comment by Max-Spec** [comment]
This is in up-to-date tModLoader 1.3.

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
