### ISSUE TITLE
Projectile Error?

### ISSUE THREAD

**Issue by Ritsuuu1** [Mirsario/TerrariaOverhaul#76]
Looking at server log, it says "[14:13:56] [1/INFO] [TerrariaOverhaul]: [ProjectileLoader] NAN in unnamed vector: [NaN,NaN]."

I think it's because of Projectiles from mobs because when we tried to shoot with our arrows, there's no error showing up.

Mods Used:
Terraria Overhaul
Smart Doors
Better Reforges
Fargo's Souls Mod
AlchemistNPC
Fargo's Both Evils
Fargo's Mutant Mod
Recipe Browser
Which Mod Is This From?
Boss Checklist
Calamity Mod

Server Log:
[server.log](https://github.com/Mirsario/TerrariaOverhaul/files/7518272/server.log)

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
