### ISSUE TITLE
Crash when refocusing on TML from minimized

### ISSUE THREAD

**Issue by scottwilson0308** [Mirsario/TerrariaOverhaul#77]
I think the log will contain all the info that you'd need, please let me know if there's any other information you need! I tried searching the web for what could be causing the error (XNA Framework Reach profile requires TextureAddressMode to be Clamp when using texture sizes that are not powers of two.) The only idea that I've got is that Overhaul isn't compatible with my practically nonexistent graphics card, except that I can't find other people complaining about this error, and I'm not the only one running Overhaul with a trash integrated card. Hope I can help somehow, thanks in advance!

[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/7599215/client.log)

Edit: Forgot to mention that this happens when TML config Support4K is set to false.

[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/7599331/client.log)

is what I get when it's set to true.

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
