### ISSUE TITLE
Cannot load world past configuring liquids

### ISSUE THREAD

**Issue by andrey6498** [Mirsario/TerrariaOverhaul#78]
Mod v4.5.3
Tml v0.11.8.5
I'll attach logs in 5 min next msg
New char new world

**Comment by andrey6498** [comment]
[client.log](https://github.com/Mirsario/TerrariaOverhaul/files/7642749/client.log)

clean logs no other mods enabled
Game freezes for a moment after "finishing" loading liquids and stops at 99%

**Comment by andrey6498** [comment]
seems to be tied to local worlds(start single player instead of server)

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
