### ISSUE TITLE
Item dupe glitch

### ISSUE THREAD

**Issue by andrey6498** [Mirsario/TerrariaOverhaul#79]
Rolling through door causes it to open and after that this door starts to duplicate all non base block(furniture, any complex block etc) type objects within approx 5 block radius on closing this exact door. 
Repeats until replacing items that are being duplicated.
Steps to reproduce:
1. Place something like a crafting station near door
2. Close this door and roll through it causing door to open
3. Now trying to close door will result in duplicating items

Mod v4.5.3
Tml v0.11.8.5

**Comment by andrey6498** [comment]
*probably breaks anything that requires solid block/wall to be placed on*

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
