### ISSUE TITLE
Crash on world save - total data loss

### ISSUE THREAD

**Issue by sirati** [Mirsario/TerrariaOverhaul#80]
During LAN multiplayer all clients were suddenly disconnected and the server crashed. 
From the crashlog is it clear that it was due to an uncaught exception during world save. The trace points at the fire system. As the crash happened during a world save, all progress made was unfortunately lost.

For me it is unclear if this is due to another error first shutting down the server or if the server tried to do an autosave.
here is the crashlog: https://pastebin.com/7Ed2u0qL

**Comment by Mirsario** [comment]
Should be fixed with the just-released life support that is [4.5.4](https://www.patreon.com/posts/64520453).

**Comment by sirati** [comment]
Thanks a lot 😊❤️
