### ISSUE TITLE
Nothing i mine or kill drops anything.

### ISSUE THREAD

**Issue by NateBushbaby** [Mirsario/TerrariaOverhaul#81]
[Terraria Overhaul_ Janitor Simulator 2022-01-18 20-18-41.zip](https://github.com/Mirsario/TerrariaOverhaul/files/7893821/Terraria.Overhaul_.Janitor.Simulator.2022-01-18.20-18-41.zip)
video included in a zip because its too big to upload normally. Ive been having to flipflop between versions because of this. Please help!

**Comment by BloodWorkXGaming** [comment]
I have the same issue. Did you find a fix yet?

My mod List:
![grafik](https://user-images.githubusercontent.com/8137062/161388864-9b745de4-699b-42b7-a2d5-96a1bc85f845.png)

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
