### ISSUE TITLE
[5.0] Boomerangs have reversed knockback

### ISSUE THREAD

**Issue by Mirsario** [Mirsario/TerrariaOverhaul#91]
Enemies are pulled towards the player, rather than being knocked back. Not sure why, yet.

https://user-images.githubusercontent.com/6795251/166921107-01b9629d-a29e-4c6a-896f-db82fa16cc5a.mp4

**Comment by Paladynee** [comment]
would be pretty cool if it was a feature since boomerangs come back

**Comment by Mirsario** [comment]
Enemies are obviously still knocked towards the player when the boomerang is returning.
